### ISSUE TITLE
Client crash on connecting after update from 2.2.2x to 2.2.3A on primitivemobs

### ISSUE THREAD

**Issue by buizerd** [Beyond-Reality/BeyondRealityModPack#183]
http://pastebin.com/0FxAUcSF

**Comment by OptimusDonut** [comment]
Do you have Optifine installed or fastcraft?

**Comment by buizerd** [comment]
Nope and exactly the same modlist as before the update

**Comment by OptimusDonut** [comment]
Odd because I have seen this issue in the past which was do to the
chameleon in primitive mobs not working with them to mods.

**Comment by buizerd** [comment]
Removed the whole instance and reinstalled it. No effect unfortunately

**Comment by Suterusu1337** [comment]
This isn't going to be fixed by reinstalling anything.  You have a corrupt entity basically in your world save.  I see this more often than not with MFR grinders causing mobs to get broken.  This happens with _any_ entity, pig, chicken, mobs from other mods.

You have on semi-easy way to fix it.  Open the world in mcedit (program, google it) and find the entity at "Entity's Exact location: 745.50, 64.00, -731.38"

Using mcedit, delete the entity and save.

This will remove the bugged entity from the world save and you will be able to once again launch the game without crashing.

**Comment by Dominance** [comment]
Ended up just yanking the mod off the server. I really do not want to remove it from the pack how ever. It just is not being updated enough and has so many issues, over half the mod is disabled in BR as it is already.

**Comment by Dominance** [comment]
Going to be removing primitive mobs if nothing is updated soon.
