### ISSUE TITLE
Irradiated Comb

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#394]
Irradiated Comb have no outbut in a centrefige

![2016-04-12_13 14 01](https://cloud.githubusercontent.com/assets/15316448/14458292/80d7ac26-00b0-11e6-9f90-c45a2e3a4c4e.png)
![2016-04-12_13 14 03](https://cloud.githubusercontent.com/assets/15316448/14458306/8e2df9fc-00b0-11e6-9ca7-e417472c3dda.png)

**Comment by leagris** [comment]
Hello @Ldmf 

Irradiated combs have no output either in forestry centrifuges. This is intentional.
If you are currently breeding avenging bees and next species, I suggest you take necessary protections by moving such bees housing very far from anything you want intact, because the effect of these later bees, is to destroy blocks in range.

**Comment by Ldmf** [comment]
thx 4 the info :) i was thinking it was an error ^^
