### ISSUE TITLE
Ender quarry (no Upgrade) (SSP)

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#396]
The ender quarry starts afer a save and re enter the world 5 or 6 chunks from the orgiginal stop energy is enoth

idk wath it curs or how too fix it

**Comment by leagris** [comment]
@ldmf Not sure I understand exactly what happens here. Surely the EnderQuarry has enough bugs on its own, that I would not be surprised it is just one more. Certainly related to current position not correctly saved or chunk unloading/reloading related.

Next BeyondReality will use EnderIO-1.7.10-2.3.0.424_beta or newer instead of EnderIO-1.7.10-2.3.0.422_beta. Nothing found related to EnderQuarry in [EnderIO-1.7.10-2.3.0.424_beta Changelog](http://minecraft.curseforge.com/projects/ender-io/files/2284032#additional-files).

As EnderIO development moved to 1.8+, expect build 424 to be the ultimate one for 1.7.10.

**Comment by spacebuilder2020** [comment]
Isn't the Ender Quarry from Extra Utilities, not Ender IO?

**Comment by Ldmf** [comment]
@spacebuilder2020 it's from Extra Utilities you are korekt

@leagris 
> EnderQuarry has enough bugs

Thx 4 the info :)

**Comment by leagris** [comment]
OMG, where is my brain? ;D

**Comment by Ldmf** [comment]
@leagris Zombies eaten your brain ^^ *irony off*

no body is perfect or so ;)

**Comment by leagris** [comment]
Well, EnderQuary has behavior issues with past and current versions. Like skipping fluid blocks, causing sand/gravel falls despite it mines from top to bottom.

Unfortunately, no update either for ExtraUtilities and forever version 1.2.12 as it also moved development to 1.8+ http://minecraft.curseforge.com/projects/extra-utilities.

EnderQuarry has [open issues that are more than a year old[(https://github.com/rwtema/extrautilities/issues?q=is%3Aissue+is%3Aopen+quarry) and not fixed.
I really can't help you more on this, other than redirect you to:
https://github.com/rwtema/extrautilities/issues

**Comment by Ldmf** [comment]
ok thx :)
