### ISSUE TITLE
dark iron rods + integrated circuit in the assembler.

### ISSUE THREAD

**Issue by docteurmystere** [Beyond-Reality/BeyondRealityModPack#405]
the recipe for dark iron bars defined in minetweaker works, but the integrated circuit gets used. adding "* 0" in the relative entry in enderio.zs has no effect, while adding ".reuse" results in an error loading the script. i haven't tested the other tweaker-added recipes with ic's yet (plywood and a couple others).

**Comment by spacebuilder2020** [comment]
lol

**Comment by leagris** [comment]
You need to restart server/game once you have add * 0 to zs script.
Because Gregtech will not re-register modified recipe with same output.
Re-download this [Configs.zip](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/Configs.zip) and unzip into your server.
I have just fixed this yesterday: https://github.com/Beyond-Reality/BeyondRealityModPack/commit/38a5e62346e6d1506f4308d1abc7bfc5d1b35714

**Comment by spacebuilder2020** [comment]
xD, also anything that modifies ore dictionary will also require a restart to take effect.

**Comment by docteurmystere** [comment]
well, i imagined that gttweaker worked no different than standard minetweaker. could have googled more. man, i feel so stupid right now.
thank you guys,

**Comment by leagris** [comment]
Fixed long ago
