### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#406]
So 5x Light Fuel Cell + 1 Heavy Fuel cell in the mixer forms 6 diesel cells.

Light Fuel has a fuel value of 256,000 EU
Heavy Fuel has a value of 196,000 EU

So why does Diesel only have a value of 128,000 EU

**Comment by leagris** [comment]
It is a Gregtech issue yes.
You should open a issue at @Blood-Asp 's repository https://github.com/Blood-Asp/GT5-Unofficial/issues

Those fuels value would need re-balancing or it does not make sense to produce Diesel, or it is for Railcraft compatibility only.

In the mean time, you should probably burn Light Fuel into Gregtech Diesel generators instead of trying to craft less efficient Railcraft Diesel Fuel.

Though Nitro-Diesel at 256,000 is also unbalanced against LightFuel.

Given the current work on Large Diesel Generators, I'd say it would be wise to propose Diesel fuels with more Burnvalue. As even with high efficiency gain, 256000 EU for 1000l of fuel will look underpowered when your goal is EV or IV power.

See:
https://github.com/Blood-Asp/GT5-Unofficial/pull/500

**Comment by spacebuilder2020** [comment]
Just noticed it is only diesel that is unbalanced.  Nitro-Diesel has a value of 512,000

**Comment by Blood-Asp** [comment]
It is only for railcraft(and other mods) compatibility.

**Comment by spacebuilder2020** [comment]
Ok, this is not a bug.
