### ISSUE TITLE
[Question] Bees

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#436]
![2016-09-25_21 56 04](https://cloud.githubusercontent.com/assets/15316448/18817821/ea11f4b6-836a-11e6-9972-0b667b2b883a.png)

I think it i a error or sonthing like that 

allmost any bee has it

BR: **2.4.1-r4**

**Comment by leagris** [comment]
I don't understand what is the issue?

**Comment by Ldmf** [comment]
the tungstenbee has 2 main out puts i thin the tungsten come is a spec out put 4 the bee
some more bees has the same thing

**Comment by buizerd** [comment]
I think what Ldmf is trying to say is that the Tungsten bee produces two combs and has no specialty where other bees do have specialties :-) I hope this is intentional though where specials are quite annoying where they are only produced when both temperature and humidity of the environment match the bee exactly (despite their tolerance)

**Comment by leagris** [comment]
Yes it is intentional for balance.
Shards and other rare or non renewable products are on specialty.
So player need to invest extra efforts either with Alveary upgrades, or with Industrial Apiary upgrades, or find a proper biome environment for its production bees.

Tungsten is quite common especially if you process lava so it remains onto main product.

**Comment by Ldmf** [comment]
ah ok thx 4 :)
